name = "newsnow-project"  # 你的项目名称
type = "javascript"

[[d1_databases]]
binding = "NEWSNOW_DB"
database_name = "newsnow_db"  # 替换为你创建的数据库名称
database_id = "311d3107-ae10-45a1-849e-120157e4c32a"      # 替换为你创建的数据库 ID
